### ISSUE TITLE
Not anymore working after upgrade to 2022.3.2

### ISSUE THREAD

**Issue by michaelhenningersrb** [plakna/ha-lg-hombot#1]
Hi,

I updated my homeassistant installation yesterday to 2022.3.2

Since that, this integration is not working anymore.

Any ideas or experiences? I do not see a error message in the logs.

BR, Michael

**Comment by michaelhenningersrb** [comment]
Maybe this blog entry helps:
https://www.home-assistant.io/blog/2022/03/02/release-20223/#updates-for-custom-integration-developers

**Comment by sj3fk3-moof** [comment]
Logger: homeassistant.components.vacuum
Source: custom_components/lg_hombot/vacuum.py:227
Integration: Vacuum ([documentation](https://www.home-assistant.io/integrations/vacuum), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vacuum%22))
First occurred: 09:12:39 (1 occurrences)
Last logged: 09:12:39

lg_hombot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/config/custom_components/lg_hombot/vacuum.py", line 227, in async_update
    with async_timeout.timeout(10, loop=self.hass.loop):
TypeError: timeout() got an unexpected keyword argument 'loop'

**Comment by plakna** [comment]
Hi,

I just released a quick and dirty hotfix. It should work again.

Btw: I'm working on a "clean" update right now. With the release of the "clean" update, the warnings in the log should also disappear. When I'm done, I'd like to make the update available via HACS. But this will take a little while.
